export const en = {
  home: "Home",
  domains: "Domains",
  monitor: "Monitoring",
  proxy: "Proxy",
  policy_group: "Policy Management",
  apis: "APIs",
  dashboard: "Dashboard",
  regist: "Regist",
  groups: "Groups",
  logs: "Logs",
  settings: "Settings",
  setup: "Setup",
  inspector: "UX Policy",
  schema: "Schema",
  server_logs: "Server Logs",
  mocking: "Mocking",
} as const;
