export const policiesEn = {
  title: "Guide Management",
  subtitle: "Manage UI/UX guides and generate professional reports.",
  filterAll: "All Domains",
  filterUnmatched: "Unmatched",
  searchPlaceholder: "Search by title, description, or selector...",
  noPolicies: "No guides found.",
  coverageNone: "This pattern does not match any registered domain. Check the host pattern.",
  coverageGap: "Some hosts in the same group are not covered.",
  capturedOn: "Captured on",
  appliedHosts: "Applies to",
  exportJson: "Export JSON",
  importJson: "Import JSON",
  exportPdf: "Generate PDF Report",
  policyCount: "guides",
  edit: "Edit",
  delete: "Delete",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "Last Updated",
  visitSite: "Visit Site",
  pdfFileName: "Guide_Report",
  deleteConfirm: "Are you sure you want to delete this guide?",
  importSuccess: "guides imported successfully.",
  exportSuccess: "Guide data saved as JSON.",
  zoom: "Zoom",
  save: "Save",
  cancel: "Cancel",
  roleLabel: "Element Title",
  descLabel: "Guide Details",
  displayOptions: "Report Fields",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "Manage Mode",
  viewPreview: "Report Preview",
  editPolicy: "Edit Guide Info",
  urlLabel: "Capture URL (origin)",
  domainLabel: "Capture host (origin)",
  hostPatternLabel: "Host Pattern",
  pathPatternLabel: "Path Pattern",
  hostPatternPlaceholder: "e.g. www.modetour.com, www.modetour.dev",
  pathPatternPlaceholder: "e.g. /products/*, /checkout (** = recursive)",
  patternHelp:
    "Matching uses Host Pattern only. domain/url record where the guide was captured. Separate multiple hosts with commas.",
};
