export const policiesKo = {
  title: "가이드 관리",
  subtitle: "서비스별로 정의된 UI/UX 가이드를 관리하고 리포트를 생성합니다.",
  filterAll: "전체 도메인",
  searchPlaceholder: "가이드명, 설명, 선택자 검색...",
  noPolicies: "검색 결과가 없습니다.",
  exportJson: "JSON 백업",
  importJson: "데이터 복원",
  exportPdf: "PDF 리포트 생성",
  policyCount: "개의 가이드",
  edit: "수정",
  delete: "삭제",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "최종 수정",
  visitSite: "사이트 방문",
  pdfFileName: "가이드_리포트",
  deleteConfirm: "정말 이 가이드를 삭제하시겠습니까?",
  importSuccess: "개의 가이드를 성공적으로 가져왔습니다.",
  exportSuccess: "가이드 데이터가 JSON 파일로 저장되었습니다.",
  zoom: "확대",
  save: "저장",
  cancel: "취소",
  roleLabel: "요소 명칭",
  descLabel: "가이드 내용",
  displayOptions: "리포트 노출 항목",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "관리 모드",
  viewPreview: "리포트 미리보기",
  editPolicy: "가이드 정보 수정",
  urlLabel: "연결된 URL",
  domainLabel: "그룹 도메인 (Domain)",
  hostPatternLabel: "호스트 매칭 패턴 (Host Pattern)",
  pathPatternLabel: "경로 매칭 패턴 (Path Pattern)",
  hostPatternPlaceholder: "예: *.modetour.dev, localhost (* = 와일드카드)",
  pathPatternPlaceholder: "예: /products/*, /checkout (** = 전체 하위 경로)",
  patternHelp: "와일드카드(*)를 사용하여 여러 도메인 및 경로에 동일한 가이드를 동적으로 적용할 수 있습니다.",
};
