export const policiesKo = {
  title: "가이드 관리",
  subtitle: "서비스별로 정의된 UI/UX 가이드를 관리하고 리포트를 생성합니다.",
  filterAll: "전체 도메인",
  filterUnmatched: "미매칭",
  searchPlaceholder: "가이드명, 설명, 선택자 검색...",
  noPolicies: "검색 결과가 없습니다.",
  coverageNone: "등록된 도메인과 맞지 않습니다. Host Pattern을 확인하세요.",
  coverageGap: "같은 그룹에 적용되지 않는 호스트가 있습니다.",
  capturedOn: "캡처",
  appliedHosts: "적용 호스트",
  exportJson: "JSON 백업",
  importJson: "데이터 복원",
  exportPdf: "PDF 리포트 생성",
  policyCount: "개의 가이드",
  edit: "수정",
  delete: "삭제",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "최종 수정",
  visitSite: "사이트 방문",
  pdfFileName: "가이드_리포트",
  deleteConfirm: "정말 이 가이드를 삭제하시겠습니까?",
  importSuccess: "개의 가이드를 성공적으로 가져왔습니다.",
  exportSuccess: "가이드 데이터가 JSON 파일로 저장되었습니다.",
  zoom: "확대",
  save: "저장",
  cancel: "취소",
  roleLabel: "요소 명칭",
  descLabel: "가이드 내용",
  displayOptions: "리포트 노출 항목",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "관리 모드",
  viewPreview: "리포트 미리보기",
  editPolicy: "가이드 정보 수정",
  urlLabel: "캡처 URL (출처)",
  domainLabel: "캡처 호스트 (출처)",
  hostPatternLabel: "호스트 매칭 패턴 (Host Pattern)",
  pathPatternLabel: "경로 매칭 패턴 (Path Pattern)",
  hostPatternPlaceholder: "예: www.modetour.com, www.modetour.dev",
  pathPatternPlaceholder: "예: /products/*, /checkout (** = 전체 하위 경로)",
  patternHelp:
    "적용 범위는 Host Pattern만 사용합니다. domain/url은 이 가이드를 만든 페이지 출처입니다. 콤마로 여러 호스트를 넣을 수 있습니다.",
};
