export const en = {
  title: "Mocking",
  subtitle: "Manage API test scenarios and mock rules.",
  scenarios: "Scenarios",
  mockRules: "Mock Rules",
  createScenario: "Create Scenario",
  editScenario: "Edit Scenario",
  deleteScenario: "Delete Scenario",
  name: "Name",
  description: "Description",
  save: "Save",
  cancel: "Cancel",
  deleteConfirm: "Are you sure you want to delete this scenario?",
  addRule: "Add Rule",
  editRule: "Edit Rule",
  method: "Method",
  urlPattern: "URL Pattern",
  status: "Status",
  enabled: "Enabled",
  disabled: "Disabled",
  headers: "Headers",
  host: "Host (Origin)",
  body: "Body",
  deleteRuleConfirm: "Are you sure you want to delete this rule?",
  noScenarios: "No Scenarios",
  noScenariosDesc: "Create a scenario to start mocking API responses.",
  noRules: "No Rules",
  noRulesDesc: "Add mock rules to this scenario.",
  createRuleSuccess: "Mock rule created.",
  updateRuleSuccess: "Mock rule updated.",
  deleteRuleSuccess: "Mock rule deleted.",
  createScenarioSuccess: "Scenario created.",
  updateScenarioSuccess: "Scenario updated.",
  deleteScenarioSuccess: "Scenario deleted.",
  saveAsMockRule: "Save as Mock Rule",
  selectScenario: "Select Scenario",
};
