export const ko = {
  title: "모킹 (Mocking)",
  subtitle: "API 테스트 시나리오 및 모킹 룰을 관리합니다.",
  scenarios: "시나리오",
  mockRules: "모킹 룰",
  createScenario: "시나리오 생성",
  editScenario: "시나리오 수정",
  deleteScenario: "시나리오 삭제",
  name: "이름",
  description: "설명",
  save: "저장",
  cancel: "취소",
  deleteConfirm: "이 시나리오를 삭제하시겠습니까?",
  addRule: "룰 추가",
  editRule: "룰 수정",
  method: "메서드",
  urlPattern: "URL 패턴",
  status: "상태 코드",
  enabled: "활성화",
  disabled: "비활성화",
  headers: "헤더",
  host: "호스트 (Origin)",
  body: "바디",
  deleteRuleConfirm: "이 모킹 룰을 삭제하시겠습니까?",
  noScenarios: "시나리오 없음",
  noScenariosDesc: "API 응답 모킹을 시작하려면 시나리오를 생성하세요.",
  noRules: "룰 없음",
  noRulesDesc: "이 시나리오에 모킹 룰을 추가하세요.",
  createRuleSuccess: "모킹 룰이 생성되었습니다.",
  updateRuleSuccess: "모킹 룰이 수정되었습니다.",
  deleteRuleSuccess: "모킹 룰이 삭제되었습니다.",
  createScenarioSuccess: "시나리오가 생성되었습니다.",
  updateScenarioSuccess: "시나리오가 수정되었습니다.",
  deleteScenarioSuccess: "시나리오가 삭제되었습니다.",
  saveAsMockRule: "모킹 룰로 저장",
  selectScenario: "시나리오 선택",
};
