export const en = {
  title: "Guide Management",
  subtitle: "Manage UI/UX guides and generate professional reports.",
  filterAll: "All Domains",
  searchPlaceholder: "Search by title, description, or selector...",
  noPolicies: "No guides found.",
  exportJson: "Export JSON",
  importJson: "Import JSON",
  exportPdf: "Generate PDF Report",
  policyCount: "guides",
  edit: "Edit",
  delete: "Delete",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "Last Updated",
  visitSite: "Visit Site",
  pdfFileName: "Guide_Report",
  deleteConfirm: "Are you sure you want to delete this guide?",
  importSuccess: "guides imported successfully.",
  exportSuccess: "Guide data saved as JSON.",
  zoom: "Zoom",
  save: "Save",
  cancel: "Cancel",
  roleLabel: "Element Title",
  descLabel: "Guide Details",
  displayOptions: "Report Fields",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "Manage Mode",
  viewPreview: "Report Preview",
  editPolicy: "Edit Guide Info",
  urlLabel: "Linked URL",
  domainLabel: "Group Domain",
  hostPatternLabel: "Host Pattern",
  pathPatternLabel: "Path Pattern",
  hostPatternPlaceholder: "e.g. *.modetour.dev, localhost (* = wildcard)",
  pathPatternPlaceholder: "e.g. /products/*, /checkout (** = recursive)",
  patternHelp: "Use wildcards (*) to dynamically match guides across multiple hosts and path patterns.",
};
