export const en = {
  title: "UX Policy Management",
  subtitle: "Manage UI/UX policies and generate professional reports.",
  filterAll: "All Domains",
  searchPlaceholder: "Search by role, description, or selector...",
  noPolicies: "No policies found.",
  exportJson: "Export JSON",
  importJson: "Import JSON",
  exportPdf: "Generate PDF Report",
  policyCount: "policies",
  edit: "Edit",
  delete: "Delete",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "Last Updated",
  visitSite: "Visit Site",
  pdfFileName: "UX_Policy_Report",
  deleteConfirm: "Are you sure you want to delete this policy?",
  importSuccess: "policies imported successfully.",
  exportSuccess: "Policy data saved as JSON.",
  zoom: "Zoom",
  save: "Save",
  cancel: "Cancel",
  roleLabel: "Element Title",
  descLabel: "Policy Details",
  displayOptions: "Report Fields",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "Manage Mode",
  viewPreview: "Report Preview",
  editPolicy: "Edit Policy Info",
  urlLabel: "Linked URL",
};
