// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	registDomains: (payload: RegistDomainsPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("regist_domains", { payload })),
	getDomains: () => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("get_domains")),
	removeDomains: (payload: RemoveDomainsPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("remove_domains", { payload })),
	getDomainById: (payload: GetDomainByIdPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("get_domain_by_id", { payload })),
	updateDomainById: (payload: UpdateDomainByIdPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("update_domain_by_id", { payload })),
	importDomains: (payload: ImportDomainsPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("import_domains", { payload })),
	clearAllDomains: () => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("clear_all_domains")),
	getLatestStatus: () => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("get_latest_status")),
	checkDomainStatus: () => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("check_domain_status")),
	getDomainStatusLogs: (payload: GetDomainStatusLogsPayload) => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("get_domain_status_logs", { payload })),
	getDomainGroupLinks: () => typedError<ApiResponse<DomainGroupLink[]>, string>(__TAURI_INVOKE("get_domain_group_links")),
	setDomainGroups: (payload: SetDomainGroupsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("set_domain_groups", { payload })),
	setGroupDomains: (payload: SetGroupDomainsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("set_group_domains", { payload })),
	getDomainsByGroup: (payload: GetDomainsByGroupPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("get_domains_by_group", { payload })),
	getGroupsForDomain: (payload: GetGroupsForDomainPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("get_groups_for_domain", { payload })),
	createGroup: (payload: CreateGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("create_group", { payload })),
	getGroups: () => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("get_groups")),
	deleteGroup: (payload: DeleteGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("delete_group", { payload })),
	updateGroup: (payload: UpdateGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("update_group", { payload })),
	getLocalRoutes: () => typedError<ApiResponse<LocalRoute[]>, string>(__TAURI_INVOKE("get_local_routes")),
	addLocalRoute: (payload: AddLocalRoutePayload) => typedError<ApiResponse<LocalRoute>, string>(__TAURI_INVOKE("add_local_route", { payload })),
	updateLocalRoute: (payload: UpdateLocalRoutePayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("update_local_route", { payload })),
	removeLocalRoute: (payload: RemoveLocalRoutePayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("remove_local_route", { payload })),
	setLocalRouteEnabled: (payload: SetLocalRouteEnabledPayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("set_local_route_enabled", { payload })),
	getProxyStatus: () => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("get_proxy_status")),
	startLocalProxy: (payload: {
	port: number | null,
} | null) => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("start_local_proxy", { payload })),
	stopLocalProxy: () => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("stop_local_proxy")),
	getProxySettings: () => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("get_proxy_settings")),
	setProxyDnsServer: (payload: SetProxyDnsServerPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_dns_server", { payload })),
	setProxyPort: (payload: SetProxyPortPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_port", { payload })),
	setProxyReversePorts: (payload: SetProxyReversePortsPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_reverse_ports", { payload })),
	/**
	 *  Returns the setup page URL when proxy is running and a reverse port is configured.
	 *  Frontend can open this URL in the browser (e.g. via opener plugin).
	 */
	getProxySetupUrl: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("get_proxy_setup_url")),
	exportAllSettings: () => typedError<ApiResponse<SettingsExport_Serialize>, string>(__TAURI_INVOKE("export_all_settings")),
	importAllSettings: (payload: SettingsExport_Deserialize) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("import_all_settings", { payload })),
	saveRootCa: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("save_root_ca")),
	getDomainMonitorList: () => typedError<ApiResponse<DomainMonitorWithUrl[]>, string>(__TAURI_INVOKE("get_domain_monitor_list")),
	setDomainMonitorCheckEnabled: (payload: SetDomainMonitorCheckEnabledPayload) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("set_domain_monitor_check_enabled", { payload })),
	/**  모든 도메인 API 로깅 링크 조회. */
	getDomainApiLoggingLinks: () => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("get_domain_api_logging_links")),
	/**  도메인 API 로깅 설정 추가/변경. */
	setDomainApiLogging: (payload: SetDomainApiLoggingPayload) => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("set_domain_api_logging", { payload })),
	/**  도메인 API 로깅 설정 제거. */
	removeDomainApiLogging: (payload: RemoveDomainApiLoggingPayload) => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("remove_domain_api_logging", { payload })),
	/**  Schema URL에서 JSON/YAML을 다운로드하여 로컬 저장. */
	downloadApiSchema: (payload: DownloadApiSchemaPayload) => typedError<ApiResponse<SchemaDownloadResult>, string>(__TAURI_INVOKE("download_api_schema", { payload })),
	/**  로컬에 저장된 Schema 내용 조회. */
	getApiSchemaContent: (payload: GetApiSchemaPayload) => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_api_schema_content", { payload })),
	/**
	 *  임의의 HTTP 요청을 전송하고 응답을 반환 (Schema Try-it-out).
	 *  네트워크 에러도 ApiResponse로 감싸서 반환 (Tauri invoke 예외 대신 FE에서 처리 가능).
	 */
	sendApiRequest: (payload: SendApiRequestPayload) => typedError<ApiResponse<ApiRequestResult>, string>(__TAURI_INVOKE("send_api_request", { payload })),
	setLocalRoutingEnabled: (payload: SetLocalRoutingEnabledPayload) => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("set_local_routing_enabled", { payload })),
	/**  Returns the auto-start error if proxy failed to start on launch, or null if OK. */
	getProxyAutoStartError: () => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_proxy_auto_start_error")),
	/**  API 로그 날짜 목록 조회. (YYYY-MM-DD) */
	listApiLogDates: () => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("list_api_log_dates")),
	/**  특정 날짜의 API 로그 조회. */
	getApiLogs: (payload: GetApiLogsPayload) => typedError<ApiResponse<ApiLogEntry[]>, string>(__TAURI_INVOKE("get_api_logs", { payload })),
	/**  API 로그 삭제 (특정 날짜 또는 전체). */
	clearApiLogs: (payload: ClearApiLogsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("clear_api_logs", { payload })),
	openWindow: (label: string, title: string, url: string, width: number | null, height: number | null) => typedError<null, string>(__TAURI_INVOKE("open_window", { label, title, url, width, height })),
	openInspectorWindow: (url: string, script: string | null) => typedError<null, string>(__TAURI_INVOKE("open_inspector_window", { url, script })),
	openAnnotationDialog: (selector: string, content: string, tagName: string, thumbnail: string) => typedError<null, string>(__TAURI_INVOKE("open_annotation_dialog", { selector, content, tagName, thumbnail })),
	getAnnotations: () => typedError<ApiResponse<Annotation[]>, string>(__TAURI_INVOKE("get_annotations")),
	addAnnotation: (payload: Annotation) => typedError<ApiResponse<Annotation[]>, string>(__TAURI_INVOKE("add_annotation", { payload })),
	updateAnnotation: (payload: UpdateAnnotationPayload) => typedError<ApiResponse<Annotation[]>, string>(__TAURI_INVOKE("update_annotation", { payload })),
	deleteAnnotation: (payload: DeleteAnnotationPayload) => typedError<ApiResponse<Annotation[]>, string>(__TAURI_INVOKE("delete_annotation", { payload })),
	importAnnotations: (payload: ImportAnnotationsPayload) => typedError<ApiResponse<Annotation[]>, string>(__TAURI_INVOKE("import_annotations", { payload })),
	setGlobalInspectorEnabled: (payload: boolean) => typedError<null, string>(__TAURI_INVOKE("set_global_inspector_enabled", { payload })),
	getGlobalInspectorEnabled: () => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("get_global_inspector_enabled")),
	getInjectionDomains: () => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("get_injection_domains")),
	setInjectionDomains: (payload: SetInjectionDomainsPayload) => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("set_injection_domains", { payload })),
	getScenarios: () => typedError<ApiResponse<Scenario[]>, string>(__TAURI_INVOKE("get_scenarios")),
	createScenario: (payload: CreateScenarioPayload) => typedError<ApiResponse<Scenario>, string>(__TAURI_INVOKE("create_scenario", { payload })),
	updateScenario: (id: string, name: string | null, description: string | null, enabled: boolean | null) => typedError<Scenario, string>(__TAURI_INVOKE("update_scenario", { id, name, description, enabled })),
	deleteScenario: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_scenario", { id })),
	getMockRules: () => typedError<ApiResponse<MockRule[]>, string>(__TAURI_INVOKE("get_mock_rules")),
	getMockRulesByScenario: (payload: GetMockRulesByScenarioPayload) => typedError<ApiResponse<MockRule[]>, string>(__TAURI_INVOKE("get_mock_rules_by_scenario", { payload })),
	createMockRule: (payload: CreateMockRulePayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("create_mock_rule", { payload })),
	updateMockRule: (payload: UpdateMockRulePayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("update_mock_rule", { payload })),
	deleteMockRule: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_mock_rule", { id })),
	createMockRuleFromLog: (payload: CreateMockFromLogPayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("create_mock_rule_from_log", { payload })),
	getMockingStatus: () => typedError<ApiResponse<MockingSettings>, string>(__TAURI_INVOKE("get_mocking_status")),
	setMockingEnabled: (payload: SetMockingEnabledPayload) => typedError<ApiResponse<MockingSettings>, string>(__TAURI_INVOKE("set_mocking_enabled", { payload })),
	setScenarioEnabled: (id: string, enabled: boolean) => typedError<Scenario[], string>(__TAURI_INVOKE("set_scenario_enabled", { id, enabled })),
	getTailscaleIp: () => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_tailscale_ip")),
	startCloudflareTunnel: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("start_cloudflare_tunnel")),
	stopCloudflareTunnel: () => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("stop_cloudflare_tunnel")),
	checkAdbStatus: () => typedError<ApiResponse<AdbStatus>, string>(__TAURI_INVOKE("check_adb_status")),
	startUsbReverse: (port: number) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("start_usb_reverse", { port })),
	stopUsbReverse: (port: number) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("stop_usb_reverse", { port })),
};

/* Types */
export type AdbStatus = {
	found: boolean,
	path: string | null,
	devices: string[],
};

export type AddLocalRoutePayload = {
	domain: string,
	targetHost: string,
	targetPort: number,
};

export type Annotation = {
	id: string,
	selector: string,
	content: string,
	tagName: string,
	thumbnail: string,
	role: string,
	description: string,
	timestamp: number | null,
	domain?: string,
	url?: string,
};

export type ApiLogEntry = {
	id: string,
	timestamp: string,
	method: string,
	url: string,
	host: string,
	path: string,
	status_code: number | null,
	request_headers: { [key in string]: string } | null,
	request_body: string | null,
	response_headers: { [key in string]: string } | null,
	response_body: string | null,
};

export type ApiRequestResult = {
	statusCode: number,
	headers: { [key in string]: string },
	body: string,
	elapsedMs: number | null,
};

export type ApiResponse<T> = {
	message: string,
	success: boolean,
	data: T,
};

export type ClearApiLogsPayload = {
	date: string | null,
};

export type CreateGroupPayload = {
	name: string,
};

export type CreateMockFromLogPayload = {
	logId: string,
	scenarioId: string,
	name: string,
	logDate: string,
};

export type CreateMockRulePayload = {
	name: string,
	scenarioId: string,
	host: string | null,
	method: string,
	urlPattern: string,
	responseStatus: number,
	responseHeaders: { [key in string]: string },
	responseBody: string | null,
	enabled: boolean,
};

export type CreateScenarioPayload = {
	name: string,
	description: string | null,
};

export type DeleteAnnotationPayload = {
	id: string,
};

export type DeleteGroupPayload = {
	id: number,
};

export type Domain = {
	id: number,
	url: string,
};

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink = DomainApiLoggingLink_Serialize | DomainApiLoggingLink_Deserialize;

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink_Deserialize = {
	domainId: number,
	loggingEnabled?: boolean,
	bodyEnabled?: boolean,
	/**  OpenAPI/Swagger 스키마 다운로드 URL (예: https://api.example.com/swagger.json). */
	schemaUrl?: string | null,
};

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink_Serialize = {
	domainId: number,
	loggingEnabled: boolean,
	bodyEnabled: boolean,
	/**  OpenAPI/Swagger 스키마 다운로드 URL (예: https://api.example.com/swagger.json). */
	schemaUrl?: string | null,
};

export type DomainGroup = {
	id: number,
	name: string,
};

export type DomainGroupLink = {
	domain_id: number,
	group_id: number,
};

/**  Domain monitor settings (check_enabled, interval). Keyed by URL for import matching. */
export type DomainMonitorExport = {
	url: string,
	checkEnabled: boolean,
	intervalSecs: number,
};

/**  `DomainMonitorLink` + url (FE 표시용) */
export type DomainMonitorWithUrl = {
	domainId: number,
	url: string,
	checkEnabled: boolean,
	intervalSecs: number,
};

/**  체크 결과 구조. 최신은 `메모리(last_checks)`, 과거는 logs/{date}.json */
export type DomainStatusLog = {
	url: string,
	status: string,
	level: string,
	latency: number,
	ok: boolean,
	group: string,
	timestamp: string,
	errorMessage: string | null,
};

export type DownloadApiSchemaPayload = {
	domainId: number,
	/**  URL to fetch OpenAPI/Swagger schema from. */
	url: string,
};

export type GetApiLogsPayload = {
	date: string,
	domainFilter: string | null,
	methodFilter: string | null,
	hostFilter: string | null,
	exactMatch: boolean | null,
};

export type GetApiSchemaPayload = {
	domainId: number,
};

export type GetDomainByIdPayload = {
	id: number,
};

export type GetDomainStatusLogsPayload = {
	date: string,
};

export type GetDomainsByGroupPayload = {
	groupId: number,
};

export type GetGroupsForDomainPayload = {
	domainId: number,
};

export type GetMockRulesByScenarioPayload = {
	scenarioId: string,
};

export type ImportAnnotationsPayload = {
	annotations: Annotation[],
};

export type ImportDomainsPayload = {
	domains: Domain[],
};

export type LocalRoute = {
	id: number,
	/**  Hostname to match (e.g. api.example.com) */
	domain: string,
	/**  Local target host (e.g. 127.0.0.1) */
	target_host: string,
	/**  Local target port */
	target_port: number,
	enabled: boolean,
};

export type MockRule = {
	id: string,
	name: string,
	scenario_id: string,
	host: string | null,
	method: string,
	url_pattern: string,
	response_status: number,
	response_headers: { [key in string]: string },
	response_body: string | null,
	enabled: boolean,
};

export type MockingSettings = {
	enabled: boolean,
};

export type ProxySettings = {
	/**
	 *  Optional DNS server for pass-through resolution (e.g. "8.8.8.8" or "1.1.1.1:53").
	 *  When set, hosts not matching any local route are resolved via this server before forwarding.
	 */
	dns_server: string | null,
	/**  Port the local reverse proxy listens on (e.g. 8888). User-configurable to avoid conflicts. */
	proxy_port?: number,
	/**
	 *  Optional reverse HTTP port (e.g. 8080). When set, proxy listens here for direct HTTP.
	 *  No system proxy or hosts file: open <http://127.0.0.1:8080> and traffic is routed by Host (127.0.0.1 → first local route).
	 */
	reverse_http_port?: number | null,
	/**  Optional reverse HTTPS port (e.g. 8443). When set, proxy does TLS and forwards by Host. */
	reverse_https_port?: number | null,
	/**  When true, matching local routes are applied; when false, all traffic passes through. */
	local_routing_enabled?: boolean,
};

export type ProxyStatusPayload = {
	running: boolean,
	port: number,
	/**  Reverse HTTP listener port (no system proxy; use hosts + this port). */
	reverse_http_port: number | null,
	/**  Reverse HTTPS listener port (TLS by Host). */
	reverse_https_port: number | null,
	/**  When true, local routes are applied; when false, all traffic passes through. */
	local_routing_enabled: boolean,
};

export type RegistDomainsPayload = {
	urls: string[],
	groupId: number | null,
};

export type RemoveDomainApiLoggingPayload = {
	domainId: number,
};

export type RemoveDomainsPayload = {
	id: number,
};

export type RemoveLocalRoutePayload = {
	id: number,
};

export type Scenario = {
	id: string,
	name: string,
	description: string | null,
	enabled: boolean,
};

/**  Schema 다운로드 응답: 저장된 파일 내용(텍스트) 반환. */
export type SchemaDownloadResult = {
	domainId: number,
	path: string,
	sizeBytes: number | null,
	/**  처음 N 글자 미리보기 (최대 500자). */
	preview: string,
};

export type SendApiRequestPayload = {
	method: string,
	url: string,
	headers?: { [key in string]: string },
	body: string | null,
};

export type SetDomainApiLoggingPayload = {
	domainId: number,
	loggingEnabled: boolean,
	bodyEnabled: boolean,
	schemaUrl: string | null,
};

export type SetDomainGroupsPayload = {
	domainId: number,
	groupIds: number[],
};

export type SetDomainMonitorCheckEnabledPayload = {
	domainIds: number[],
	enabled: boolean,
};

export type SetGroupDomainsPayload = {
	groupId: number,
	domainIds: number[],
};

export type SetInjectionDomainsPayload = {
	domains: string[],
};

export type SetLocalRouteEnabledPayload = {
	id: number,
	enabled: boolean,
};

export type SetLocalRoutingEnabledPayload = {
	enabled: boolean,
};

export type SetMockingEnabledPayload = {
	enabled: boolean,
};

export type SetProxyDnsServerPayload = {
	dnsServer: string | null,
};

export type SetProxyPortPayload = {
	port: number,
};

export type SetProxyReversePortsPayload = {
	reverseHttpPort: number | null,
	reverseHttpsPort: number | null,
};

export type SettingsExport = SettingsExport_Serialize | SettingsExport_Deserialize;

export type SettingsExport_Deserialize = {
	version: number,
	exportedAt: string,
	domains: Domain[],
	groups: DomainGroup[],
	domainGroupLinks: DomainGroupLink[],
	localRoutes: LocalRoute[],
	proxySettings: ProxySettings,
} & {
	/**  Monitor settings per domain (check_enabled, interval). Status logs are excluded. */
	domainMonitor?: DomainMonitorExport[],
} | {
	/**  Monitor settings per domain (check_enabled, interval). Status logs are excluded. */
	domain_status?: DomainMonitorExport[],
};

export type SettingsExport_Serialize = {
	version: number,
	exportedAt: string,
	domains: Domain[],
	groups: DomainGroup[],
	domainGroupLinks: DomainGroupLink[],
	localRoutes: LocalRoute[],
	proxySettings: ProxySettings,
	/**  Monitor settings per domain (check_enabled, interval). Status logs are excluded. */
	domainMonitor: DomainMonitorExport[],
};

export type StartLocalProxyPayload = {
	port: number | null,
};

export type UpdateAnnotationPayload = {
	id: string,
	role: string,
	description: string,
};

export type UpdateDomainByIdPayload = {
	id: number,
	url: string | null,
};

export type UpdateGroupPayload = {
	id: number,
	name: string,
};

export type UpdateLocalRoutePayload = {
	id: number,
	domain: string | null,
	targetHost: string | null,
	targetPort: number | null,
	enabled: boolean | null,
};

export type UpdateMockRulePayload = {
	id: string,
	name: string | null,
	host: string | null,
	method: string | null,
	urlPattern: string | null,
	responseStatus: number | null,
	responseHeaders: { [key in string]: string } | null,
	responseBody: string | null,
	enabled: boolean | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

