import { invoke } from "@tauri-apps/api/core";
import type { MockRule, Scenario } from "../../entities/scenario/types/mocking";
import { invokeApi } from "./invoke";

export const getScenarios = async (): Promise<Scenario[]> => {
  const res = await invokeApi("get_scenarios");
  return res.data;
};

export const createScenario = async (name: string, description?: string): Promise<Scenario> => {
  const res = await invokeApi("create_scenario", { payload: { name, description } });
  return res.data;
};

export const updateScenario = (
  id: string,
  name?: string,
  description?: string,
  enabled?: boolean,
): Promise<Scenario> => {
  return invoke("update_scenario", { id, name, description, enabled });
};

export const setScenarioEnabled = (id: string, enabled: boolean): Promise<Scenario[]> => {
  return invoke("set_scenario_enabled", { id, enabled });
};

export const deleteScenario = (id: string): Promise<boolean> => {
  return invoke("delete_scenario", { id });
};

export const getMockRules = async (): Promise<MockRule[]> => {
  const res = await invokeApi("get_mock_rules");
  return res.data;
};

export const getMockRulesByScenario = async (scenarioId: string): Promise<MockRule[]> => {
  const res = await invokeApi("get_mock_rules_by_scenario", { payload: { scenarioId } });
  return res.data;
};

export const createMockRule = async (
  name: string,
  scenarioId: string,
  host: string | null,
  method: string,
  urlPattern: string,
  responseStatus: number,
  responseHeaders: Record<string, string>,
  responseBody: string | null,
  enabled: boolean,
): Promise<MockRule> => {
  const res = await invokeApi("create_mock_rule", {
    payload: {
      name,
      scenarioId,
      host,
      method,
      urlPattern,
      responseStatus,
      responseHeaders,
      responseBody,
      enabled,
    },
  });
  return res.data;
};

export const updateMockRule = async (
  id: string,
  name?: string,
  host?: string | null,
  method?: string,
  urlPattern?: string,
  responseStatus?: number,
  responseHeaders?: Record<string, string>,
  responseBody?: string | null,
  enabled?: boolean,
): Promise<MockRule> => {
  const res = await invokeApi("update_mock_rule", {
    payload: {
      id,
      name,
      host,
      method,
      urlPattern,
      responseStatus,
      responseHeaders,
      responseBody,
      enabled,
    },
  });
  return res.data;
};

export const deleteMockRule = (id: string): Promise<boolean> => {
  return invoke("delete_mock_rule", { id });
};

export const createMockRuleFromLog = async (logDate: string, logId: string, scenarioId: string): Promise<MockRule> => {
  const res = await invokeApi("create_mock_rule_from_log", {
    payload: { logDate, logId, scenarioId, name: "" }, // name will be generated by BE if empty
  });
  return res.data;
};
